# Generated by Django 5.0 on 2026-05-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cancion_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='traste_capodastro',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cancion',
            name='usa_capodastro',
            field=models.BooleanField(default=False),
        ),
    ]
